version: '2'
services:
  redis:
      image: redis
      ports:
        - "6379:6379"
  zookeeper:
      image: jplock/zookeeper
      ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
  consul:
      image: consul
      ports:
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"